USE register;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
	user_id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    fName VARCHAR(255) NOT NULL,
    lName VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    userSchool VARCHAR(255) NOT NULL,
    userName VARCHAR(255) NOT NULL,
    userPWD VARCHAR(255) NOT NULL,
    userType INTEGER NOT NULL);